<form action="<?php echo $this->getUrl('complexworld/index/edit/id/'.Mage::app()->getRequest()->getParam('id')); ?>" id="complexworldform" method="post">
    <ul class="form-list">
        <li><label>Title</label><br>
            <input class="input-text required-entry" id="title" name="title" value="<?php echo $this->getPost()->getTitle(); ?>" style="width: 250px;" type="text"></li>

        <li><label>Content</label><br>
            <input class="input-text required-entry" id="content" name="content" value="<?php echo $this->getPost()->getContent(); ?>" style="width: 250px;" type="text"></li>

    </ul><button class="form-button-alt" type="submit"><span>Edit post</span></button>
</form>
<script type="text/javascript">
    //<![CDATA[
    var complexworld = new VarienForm('complexworldform', true);
    //]]>
</script>

