<?php
/**
 * Training Helloworld Form block
 *
 * @category Training
 * @package Training_Helloworld
 * @author Vitalii Rybak <vitalii.rybak@smile-ukraine.com>
 * @copyright 2019 Smile
 */

class Training_Helloworld_Block_Adminhtml_Helloworld_Edit_Form extends Mage_Adminhtml_Block_Widget_Form
{
    /**
     * Init class
     */
    public function __construct(array $args = array())
    {
        parent::__construct($args);

        $this->setId('training_helloworld_helloworld');
        $this->setTitle($this->__('Post information'));
    }

    /**
     * Setup form fields for inserts/updates
     *
     * return Mage_Adminhtml_Block_Widget_Form
     */
    protected function _prepareForm()
    {
        $model = Mage::registry('virybpost');

        $form = new Varien_Data_Form(array(
            'id'      => 'edit_form',
            'action'  => $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))),
            'method'  => 'post'
        ));

        $fieldset = $form->addFieldset('base_fieldset', array(
            'legend'   => Mage::helper('checkout')->__('Post information'),
            'class'    => 'fieldset-wide',
        ));

        if ($model->getId()) {
            $fieldset->addField('blogpost_id', 'hidden', array(
                'name' => 'blogpost_id',
            ));
        }

        $fieldset->addField('title', 'text', array(
            'name'   => 'title',
            'label'  => Mage::helper('checkout')->__('Title'),
            'title'  => Mage::helper('checkout')->__('Title'),
        ));

        $fieldset->addField('post', 'text', array(
            'name'   => 'post',
            'label'  => Mage::helper('checkout')->__('Post'),
            'title'  => Mage::helper('checkout')->__('Post'),
        ));
        $dateFormatIso = Mage::app()->getLocale()->getDateTimeFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT);
        $fieldset->addField('date', 'date', array(
            'name'   => 'date',
            'label'  => Mage::helper('checkout')->__('Date'),
            'title'  => Mage::helper('checkout')->__('Date'),
            'image'  => $this->getSkinUrl('images/grid-cal.gif'),
            'input_format' => $dateFormatIso,
            'format'       => $dateFormatIso,
            'time' => true

        ));

        $fieldset->addField('additional', 'textarea', array(
            'name'   => 'additional',
            'label'  => Mage::helper('checkout')->__('Additional'),
            'title'  => Mage::helper('checkout')->__('Additional'),
        ));

        $form->setValues($model->getData());
        $form->setUseContainer(true);
        $this->setForm($form);

        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}
